Run in integration-test phase
casperjs/casperjs-runner-maven-plugin pull request #16
Opened 2017-01-02 11:08 UTC by vilmosnagy

As discussed in #15.

I've created an example in the `it/integration-test`  directory, but I'm not sure, that I've configured the invoker plugin right.

Closes #15 .

2017-01-02 13:06 UTC, bguerin commented
Thanks for your idea, your implementation and your share. I am ok with most of your modifications, but I you don't mind, I would have introduced an AbstractCasperJSRunnerMojo (mostly a rename from the actual CasperJSRunnerMojo), from which inherits :
- CasperJSRunnerTestMojo, mostly an empty class, just the @Mojo and the handling of the ignoreTestFailures parameter
- CasperJSRunnerIntegrationTestMojo, for your use case, which does not have the ignoreTestFailures parameter, never fails the build, and binds by default to the integration-test phase.
Doing this will simplifiy the the "client" POMs

2017-01-02 13:16 UTC, bguerin requested changes

2017-01-02 13:16 UTC, bguerin commented on src/it/casperjs-runner/integration-test/pom.xml
> +  <artifactId>ignore-failures</artifactId>
should be changed to integration-test

2017-01-02 13:16 UTC, bguerin commented on src/it/casperjs-runner/integration-test/pom.xml
> +  <name>CasperJS Runner :: ignore-failures</name>
should be changed to integration-test

2017-01-02 13:16 UTC, bguerin commented on src/main/java/com/github/casperjs/casperjsrunner/CasperJSVerifyMojo.java
> +@Mojo(name = "verify")
could you add a "defaultPhase" to verify please ?

2017-01-02 13:16 UTC, bguerin commented on src/it/casperjs-runner/integration-test/pom.xml
> +            <phase>verify</phase>
specifying the phase will be useless once you add a defaultPhase to the Mojo annotation on the Verify goal (see below)

2017-01-02 13:16 UTC, bguerin commented on src/main/java/com/github/casperjs/casperjsrunner/CasperJSRunnerMojo.java
> +            throw new MojoExecutionException("", e);
could you please add a message to help understand the exception

2017-01-02 13:16 UTC, bguerin commented on src/main/java/com/github/casperjs/casperjsrunner/CasperJSRunnerMojo.java
> +            bufferedWriter = new BufferedWriter(new FileWriter(testFailureCountFile, false));
you should take care of creating the parent directories of the destination file it they don't exist, I think this is what make CI fails

2017-01-02 21:14 UTC, bguerin approved these changes

2017-01-02 21:14 UTC, bguerin commented
Thanks for all !

2017-01-02 21:14 UTC, merged

2017-01-02 21:15 UTC, vilmosnagy commented
Thanks for the quick reply. I've just finished.

2017-01-04 08:18 UTC, bguerin commented
Release 1.0.5 out with your PR, if you need it :)